coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: 70%

ignore:
  - 'src/lib/server/auth.ts'
  - 'src/lib/server/db/index.ts'
  - 'src/lib/server/db/auth.schema.ts'
  - 'src/lib/server/db/dictionary.schema.ts'
  - 'src/lib/server/db/dictionary.views.ts'
  - 'src/lib/server/db/stage.schema.ts'
  - 'src/lib/server/db/schema.ts'
  - 'src/lib/server/services/email.ts'
  - 'src/hooks.server.ts'
  - 'src/lib/server/services/dictionary.ts'
  - 'src/routes/api/tts/**'
  - 'src/routes/api/dictionary/**'
  - 'src/routes/*/dictionary/*/+page.server.ts'
  - 'src/routes/*/dictionary/explain/**'
  # Svelte components/templates — covered by Storybook and e2e tests
  - 'src/**/*.svelte'
  # Thin data-type files with no runtime logic
  - 'src/lib/types/**'
  # Storybook example stories (not app code)
  - 'src/stories/**'
